version: "3"
services:
  postgres:
    build: .
    image: postgres:10
    expose:
      - "5432"
    ports:
      - "5432:5432"
    # volumes:
    #   - /srv/postgres:/var/lib/postgresql/data
    networks:
      - dumb

networks:
  dumb:
    driver: "bridge"
